# Generated by Django 3.1.6 on 2021-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.TextField()),
                ('model', models.TextField()),
                ('procesor', models.TextField()),
                ('verzija', models.TextField()),
                ('stanje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.TextField()),
                ('model', models.TextField()),
                ('procesor', models.TextField()),
                ('verzija', models.TextField()),
                ('stanje', models.TextField()),
            ],
        ),
    ]
