# Generated by Django 3.1.6 on 2021-02-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablet',
            old_name='stanje',
            new_name='cena',
        ),
        migrations.RenameField(
            model_name='telefon',
            old_name='stanje',
            new_name='cena',
        ),
    ]
